"""Candidate sourcing for external opportunities.

Generates external opportunity candidates from four sources (priority order):
1. Instrument catalog (dynamic discovery from IOL — PRIMARY source)
2. News (existing: news.related_assets for non-held symbols)
3. Watchlist (WATCHLIST_ASSETS config)
4. Market universe (MARKET_UNIVERSE_ASSETS config — manual fallback)

Each candidate gets a consistent set of fields:
- symbol, source_types, tracking_status
- asset_type, asset_type_status (known_valid|unknown|unsupported)
- actionable_external (tracked for follow-up)
- investable (in main_allowed + known_valid — ready for manual investment)
- actionable_reason (human-readable explanation)
- priority_score (dynamic, reflects combined sources/signals)
"""

from __future__ import annotations

from app.market.assets import resolve_asset_type
from app.recommendations.universe import classify_opportunity_status

# Pseudo-ticker blocklist: common tokens that NLP/news pipelines
# incorrectly parse as stock symbols. These are never real CEDEARs/tickers.
PSEUDO_TICKER_BLOCKLIST = frozenset({
    # C-suite / roles
    "CEO", "CFO", "CTO", "COO", "CIO",
    # Countries / regions
    "UK", "US", "EU", "UN",
    # Government / regulatory agencies
    "DOJ", "SEC", "FBI", "CIA", "FED", "IMF", "WHO",
    # Financial acronyms
    "GDP", "IPO", "ETF", "EPS", "PE", "ROI", "ROE", "ESG",
    # Exchanges (not tickers)
    "BMV", "NYSE",
    # Currencies
    "USD", "EUR", "GBP", "JPY", "BRL", "CLP", "MXN",
    # Tech / generic
    "AI", "IT", "HR", "PR", "IR",
    # Media / agencies / organizations (not investable)
    "WSJ", "NASA", "BBC", "CNN", "CNBC", "EPA", "FDA", "IRS",
    "NATO", "OPEC", "ECB", "BOJ", "RBI", "WTO", "IAEA",
    "AP", "AFP", "MIT", "UCLA", "NFL", "NBA", "FIFA",
})


def generate_external_candidates(
    news_opportunities: list[dict],
    allowed_assets: dict,
    positions: list[dict],
    catalog_map: dict[str, str] | None = None,
) -> list[dict]:
    """Build the full set of external opportunity candidates.

    Merges news-based opportunities with watchlist/universe candidates.
    Deduplicates by symbol, keeping the highest-priority entry and merging sources.

    catalog_map: symbol->asset_type from InstrumentCatalog (for classification priority).
    """
    held_symbols = {p.get("symbol") for p in positions if p.get("symbol")}
    main_allowed = allowed_assets.get("main_allowed", set())

    # --- Collect all candidates by symbol (filtering pseudo-tickers) ---
    candidates: dict[str, dict] = {}

    # 1. News-based (already generated by engine.py)
    for op in news_opportunities:
        sym = op.get("symbol", "")
        if not sym or sym in held_symbols or sym in PSEUDO_TICKER_BLOCKLIST:
            continue
        if sym not in candidates:
            candidates[sym] = _empty_candidate(sym)
        c = candidates[sym]
        c["source_types"].add("news")
        c["news_signals"].append({
            "reason": op.get("reason", ""),
            "confidence": op.get("confidence", 0.5),
            "event_type": op.get("event_type", "otro"),
            "impact": op.get("impact", "neutro"),
        })

    # 2. Catalog candidates (PRIMARY external source — dynamic from IOL discovery)
    for sym in allowed_assets.get("catalog_dynamic", set()):
        if sym in held_symbols or sym in PSEUDO_TICKER_BLOCKLIST:
            continue
        if sym not in candidates:
            candidates[sym] = _empty_candidate(sym)
        candidates[sym]["source_types"].add("catalog")

    # 3. Watchlist candidates
    for sym in allowed_assets.get("watchlist", set()):
        if sym in held_symbols or sym in PSEUDO_TICKER_BLOCKLIST:
            continue
        if sym not in candidates:
            candidates[sym] = _empty_candidate(sym)
        candidates[sym]["source_types"].add("watchlist")

    # 4. Universe candidates (includes catalog + manual)
    for sym in allowed_assets.get("universe", set()):
        if sym in held_symbols or sym in PSEUDO_TICKER_BLOCKLIST:
            continue
        if sym not in candidates:
            candidates[sym] = _empty_candidate(sym)
        candidates[sym]["source_types"].add("universe")

    # --- Score, classify, and finalize ---
    results = []
    for sym, c in candidates.items():
        tracking = classify_opportunity_status(sym, allowed_assets)
        asset_type, asset_type_status, asset_type_source = resolve_asset_type(sym, positions=positions, catalog_map=catalog_map)
        in_main = sym in main_allowed

        # --- Priority scoring (dynamic, reflects combined sources/signals) ---
        score = 0.0
        source_count = len(c["source_types"])

        if "news" in c["source_types"]:
            score += 0.4
            best_conf = max((s["confidence"] for s in c["news_signals"]), default=0.5)
            score += best_conf * 0.3
        if "catalog" in c["source_types"]:
            score += 0.25  # catalog is primary dynamic source
        if "watchlist" in c["source_types"]:
            score += 0.2
        if "universe" in c["source_types"]:
            score += 0.1

        # Boost for multiple sources
        if source_count >= 2:
            score += 0.1 * (source_count - 1)

        # Boost if type is known (more actionable)
        if asset_type_status == "known_valid":
            score += 0.05

        # Boost if in main_allowed (investable)
        if in_main:
            score += 0.1

        # --- Actionable semantics ---
        # actionable_external: requires real evidence, not just catalog/universe membership.
        # Catalog/universe alone → observed (not actionable). Promotion requires:
        #   - news signal present, OR
        #   - watchlist membership + known_valid asset type
        has_news = "news" in c["source_types"]
        watchlist_valid = "watchlist" in c["source_types"] and asset_type_status == "known_valid"
        actionable = has_news or watchlist_valid
        if asset_type_status == "unsupported":
            actionable = False

        # investable: is this ready for potential manual investment?
        #   True if in main_allowed AND type is known_valid
        investable = in_main and asset_type_status == "known_valid"

        # --- Build actionable_reason (human-readable, no contradictions) ---
        actionable_reason = _build_actionable_reason(
            tracking=tracking,
            asset_type=asset_type,
            asset_type_status=asset_type_status,
            actionable=actionable,
            investable=investable,
            in_main=in_main,
        )

        # Pick best news signal for display
        best_news = max(c["news_signals"], key=lambda s: s["confidence"], default=None) if c["news_signals"] else None

        results.append({
            "symbol": sym,
            "source_types": sorted(c["source_types"]),
            "tracking_status": tracking,
            "in_main_allowed": in_main,
            "actionable_external": actionable,
            "investable": investable,
            "actionable_reason": actionable_reason,
            "priority_score": round(score, 2),
            "asset_type": asset_type,
            "asset_type_status": asset_type_status,
            "asset_type_source": asset_type_source,
            "asset_type_valid": asset_type_status == "known_valid",
            "reason": best_news["reason"] if best_news else f"Observado desde {', '.join(sorted(c['source_types']))}",
            "confidence": best_news["confidence"] if best_news else 0.3,
            "event_type": best_news["event_type"] if best_news else "otro",
            "impact": best_news["impact"] if best_news else "neutro",
        })

    # Sort by priority descending
    results.sort(key=lambda x: x["priority_score"], reverse=True)
    return results


def _build_actionable_reason(
    *,
    tracking: str,
    asset_type: str,
    asset_type_status: str,
    actionable: bool,
    investable: bool,
    in_main: bool,
) -> str:
    """Build a consistent, non-contradictory actionable_reason string."""
    parts = []

    # Where is it tracked?
    tracking_label = {
        "catalog": "En catálogo IOL (descubierto)",
        "watchlist": "En watchlist",
        "in_universe": "En universo de mercado",
        "in_holdings": "En cartera (holding)",
        "untracked": "No rastreado",
    }.get(tracking, tracking)
    parts.append(tracking_label)

    # Asset type status
    if asset_type_status == "known_valid":
        parts.append(f"tipo {asset_type} (válido)")
    elif asset_type_status == "unknown":
        parts.append("tipo de activo pendiente de resolver")
    elif asset_type_status == "unsupported":
        parts.append(f"tipo {asset_type} no soportado")

    # Investment readiness
    if investable:
        parts.append("habilitado para inversión (en whitelist)")
    elif in_main:
        if asset_type_status == "unknown":
            parts.append("en whitelist, pero tipo desconocido")
        elif asset_type_status == "unsupported":
            parts.append("en whitelist, pero tipo no soportado")
    elif actionable:
        parts.append("habilitado para seguimiento")
    else:
        if asset_type_status != "unsupported":
            parts.append("solo observado")

    return ". ".join(parts)


def _empty_candidate(symbol: str) -> dict:
    return {
        "symbol": symbol,
        "source_types": set(),
        "news_signals": [],
    }
