"""Candidate sourcing for external opportunities.

Generates external opportunity candidates from three sources:
1. News (existing: news.related_assets for non-held symbols)
2. Watchlist (WATCHLIST_ASSETS config)
3. Market universe (MARKET_UNIVERSE_ASSETS config)

Each candidate gets:
- symbol, source_types, tracking_status, actionable_external,
  actionable_reason, priority_score, asset_type
"""

from __future__ import annotations

from app.recommendations.universe import VALID_ASSET_TYPES, classify_opportunity_status


def generate_external_candidates(
    news_opportunities: list[dict],
    allowed_assets: dict,
    positions: list[dict],
) -> list[dict]:
    """Build the full set of external opportunity candidates.

    Merges news-based opportunities with watchlist/universe candidates.
    Deduplicates by symbol, keeping the highest-priority entry and merging sources.
    """
    held_symbols = {p.get("symbol") for p in positions if p.get("symbol")}

    # Build asset_type lookup from positions
    asset_type_map: dict[str, str] = {}
    for p in positions:
        sym = p.get("symbol")
        if sym:
            asset_type_map[sym] = p.get("asset_type") or p.get("instrument_type") or "DESCONOCIDO"

    # --- Collect all candidates by symbol ---
    candidates: dict[str, dict] = {}

    # 1. News-based (already generated by engine.py)
    for op in news_opportunities:
        sym = op.get("symbol", "")
        if not sym or sym in held_symbols:
            continue
        if sym not in candidates:
            candidates[sym] = _empty_candidate(sym)
        c = candidates[sym]
        c["source_types"].add("news")
        c["news_signals"].append({
            "reason": op.get("reason", ""),
            "confidence": op.get("confidence", 0.5),
            "event_type": op.get("event_type", "otro"),
            "impact": op.get("impact", "neutro"),
        })

    # 2. Watchlist candidates
    for sym in allowed_assets.get("watchlist", set()):
        if sym in held_symbols:
            continue
        if sym not in candidates:
            candidates[sym] = _empty_candidate(sym)
        candidates[sym]["source_types"].add("watchlist")

    # 3. Universe candidates
    for sym in allowed_assets.get("universe", set()):
        if sym in held_symbols:
            continue
        if sym not in candidates:
            candidates[sym] = _empty_candidate(sym)
        candidates[sym]["source_types"].add("universe")

    # --- Score, classify, and finalize ---
    results = []
    for sym, c in candidates.items():
        tracking = classify_opportunity_status(sym, allowed_assets)
        asset_type = asset_type_map.get(sym, "DESCONOCIDO")
        asset_type_valid = asset_type in VALID_ASSET_TYPES

        # Priority scoring (simple MVP)
        score = 0.0
        if "news" in c["source_types"]:
            score += 0.4
            # Boost by best news confidence
            best_conf = max((s["confidence"] for s in c["news_signals"]), default=0.5)
            score += best_conf * 0.3
        if "watchlist" in c["source_types"]:
            score += 0.2
        if "universe" in c["source_types"]:
            score += 0.1

        # Actionable = in watchlist or universe (not just random untracked news)
        actionable = tracking in ("watchlist", "in_universe")
        if not asset_type_valid and asset_type != "DESCONOCIDO":
            actionable = False
            actionable_reason = f"Tipo de activo no soportado: {asset_type}"
        elif actionable:
            actionable_reason = f"En {tracking}, habilitado para seguimiento"
        else:
            actionable_reason = "No está en watchlist ni en universo configurado"

        # Pick best news signal for display
        best_news = max(c["news_signals"], key=lambda s: s["confidence"], default=None) if c["news_signals"] else None

        results.append({
            "symbol": sym,
            "source_types": sorted(c["source_types"]),
            "tracking_status": tracking,
            "actionable_external": actionable,
            "actionable_reason": actionable_reason,
            "priority_score": round(score, 2),
            "asset_type": asset_type,
            "asset_type_valid": asset_type_valid,
            "reason": best_news["reason"] if best_news else f"Observado desde {', '.join(sorted(c['source_types']))}",
            "confidence": best_news["confidence"] if best_news else 0.3,
            "event_type": best_news["event_type"] if best_news else "otro",
            "impact": best_news["impact"] if best_news else "neutro",
        })

    # Sort by priority descending
    results.sort(key=lambda x: x["priority_score"], reverse=True)
    return results


def _empty_candidate(symbol: str) -> dict:
    return {
        "symbol": symbol,
        "source_types": set(),
        "news_signals": [],
    }
