import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by vite build
precacheAndRoute(self.__WB_MANIFEST)

// Push event: show notification from backend payload
self.addEventListener('push', (event) => {
  const data = event.data?.json() ?? {}
  const title = data.title ?? 'Mi Finanza'
  const options = {
    body: data.body ?? '',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: [200, 100, 200],
    tag: 'mi-finanza',
    renotify: true,
    data: { url: data.deep_link ?? '/' },
  }
  event.waitUntil(self.registration.showNotification(title, options))
})

// Notification click: focus the open tab or open a new one
self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const url = event.notification.data?.url ?? '/'
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          client.navigate?.(url)
          return client.focus()
        }
      }
      return clients.openWindow(url)
    })
  )
})
